title: Specifics
url: http://riib.github.io
root: /
description: >-
  Henry Blanchette's primary blog. Topics: programming languages, computarics,
  mathematics, philosophy, evolution, game theory, game design, economics.
page-titles:
  - projects
  - media
  - categories
  - archive
  - about

collections:
  - working

# plugins:
#   - jekyll-feed

markdown: kramdown

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
